name: CI-CD Joana (self-hosted Windows, sem NSSM)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, windows, joana]

    steps:
      # 1. Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Matar instâncias antigas (Node + Java)
      - name: Encerrar Joana já em execução
        shell: powershell
        run: |
          Write-Host "Matando Node (index.js)…"
          Get-CimInstance Win32_Process `
            | Where-Object { $_.Name -eq 'node.exe' -and $_.CommandLine -match 'index\.js' } `
            | ForEach-Object { Stop-Process -Id $_.ProcessId -Force }
          Write-Host "Matando joana.jar…"
          Get-CimInstance Win32_Process `
            | Where-Object { $_.Name -eq 'java.exe' -and $_.CommandLine -match 'joana\.jar' } `
            | ForEach-Object { Stop-Process -Id $_.ProcessId -Force }

      # 3. Build JAR (Maven)
      - name: Setup JDK 17 + cache Maven
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build joana.jar
        shell: bash
        run: mvn -B clean package -DskipTests

      # 4. Build Node side
      - name: Setup Node 18 + cache
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'src/main/javascript/package-lock.json'

      - name: Install Node deps
        shell: bash
        working-directory: src/main/javascript
        run: npm ci

      - name: Build (caso tenha script)
        shell: bash
        working-directory: src/main/javascript
        run: npm run build --if-present

      # 5. Copiar artefatos para produção
      - name: Deploy artefacts
        shell: powershell
        run: |
          $prodRoot = "C:\Apps\Joana"
          $nodeDst  = "$prodRoot\js"
          $jarDst   = "$prodRoot\joana.jar"
          
          New-Item -ItemType Directory -Path $nodeDst -Force | Out-Null
          
          $jar = Get-ChildItem "$env:GITHUB_WORKSPACE\target" -Filter "joana*.jar" | Select-Object -First 1
          if (-not $jar) { Throw "JAR não encontrado." }
          Copy-Item $jar.FullName $jarDst -Force
          
          $nodeSrc = "$env:GITHUB_WORKSPACE\src\main\javascript"
          if (Test-Path "$nodeSrc\dist") {
              robocopy "$nodeSrc\dist" $nodeDst /MIR /NFL /NDL /NJH /NJS > $null
          } else {
              robocopy "$nodeSrc" $nodeDst /MIR /XF package*.json /NFL /NDL /NJH /NJS > $null
          }

      # 6. Relançar aplicações (detached)
      - name: Iniciar Joana Node + Java
        shell: powershell
        run: |
          $prodRoot = "C:\Apps\Joana"
          $nodeDir  = "$prodRoot\js"
          
          Write-Host "Iniciando Node (index.js)…"
          Start-Process -FilePath "node.exe" -WorkingDirectory $nodeDir -ArgumentList "index.js" `
                        -WindowStyle Hidden
          
          Write-Host "Iniciando joana.jar…"
          Start-Process -FilePath "java.exe" -WorkingDirectory $prodRoot -ArgumentList "-jar joana.jar" `
                        -WindowStyle Hidden
