name: CI‑CD Joana (self‑hosted Windows)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [ self-hosted, windows ]
    env:
      # usa o JDK que já existe no host
      JAVA_HOME: 'C:\Program Files\Java\jdk-21'
      PATH: 'C:\Program Files\Java\jdk-21\bin;${{ env.PATH }}'

    steps:
      # 1. Checkout
      - uses: actions/checkout@v4

      # 2. Finaliza instâncias antigas
      - name: Encerrar processos antigos
        shell: powershell
        run: |
          Get-CimInstance Win32_Process |
            Where-Object { $_.Name -eq 'node.exe' -and $_.CommandLine -match 'index\.js' } |
            ForEach-Object { Stop-Process -Id $_.ProcessId -Force }
          Get-CimInstance Win32_Process |
            Where-Object { $_.Name -eq 'java.exe' -and $_.CommandLine -match 'joana\.jar' } |
            ForEach-Object { Stop-Process -Id $_.ProcessId -Force }

      # 3. Ambiente Node
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Node deps
        working-directory: src/main/javascript
        run: npm ci

      - name: Build (caso tenha script)
        working-directory: src/main/javascript
        run: npm run build --if-present

      # 4. Build Java/Maven (usa o JDK‑21 já configurado)
      - name: Build joana.jar
        run: mvn -B clean package -DskipTests

      # 5. Deploy artefatos
      - name: Deploy artefatos
        shell: powershell
        run: |
          $prodRoot = "C:\Apps\Joana"
          $nodeDst  = "$prodRoot\js"
          $jarDst   = "$prodRoot\joana.jar"
          
          New-Item -ItemType Directory -Path $nodeDst -Force | Out-Null
          
          $jar = Get-ChildItem "$env:GITHUB_WORKSPACE\target" -Filter "joana*.jar" | Select-Object -First 1
          if (-not $jar) { Throw "JAR não encontrado." }
          Copy-Item $jar.FullName $jarDst -Force
          
          $nodeSrc = "$env:GITHUB_WORKSPACE\src\main\javascript"
          if (Test-Path "$nodeSrc\dist") {
              robocopy "$nodeSrc\dist" $nodeDst /MIR /NFL /NDL /NJH /NJS > $null
          } else {
              robocopy "$nodeSrc" $nodeDst /MIR /XF package*.json /NFL /NDL /NJH /NJS > $null

      # 6. Relança Node + Java
      - name: Iniciar Joana Node + Java
        shell: powershell
        run: |
          $prodRoot = "C:\Apps\Joana"
          $nodeDir  = "$prodRoot\js"
          Start-Process -FilePath "node.exe" -WorkingDirectory $nodeDir -ArgumentList "index.js" -WindowStyle Hidden
          Start-Process -FilePath "java.exe" -WorkingDirectory $prodRoot -ArgumentList "-jar joana.jar" -WindowStyle Hidden
