name: CI‑CD Joana (self‑hosted Windows)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [ self-hosted, windows ]

    steps:
      # 0. Expõe JDK‑21 já instalado no host
      - name: Set JAVA_HOME e PATH
        shell: powershell
        run: |
          Add-Content $env:GITHUB_ENV "JAVA_HOME=C:\Program Files\Java\jdk-21"
          Add-Content $env:GITHUB_ENV "PATH=C:\Program Files\Java\jdk-21\bin;$env:PATH"

      # 1. Checkout
      - uses: actions/checkout@v4

      # 2. Finaliza instâncias antigas
      - name: Encerrar processos antigos
        shell: powershell
        run: |
          Get-CimInstance Win32_Process |
            Where-Object { $_.Name -eq 'node.exe' -and $_.CommandLine -match 'index\.js' } |
            ForEach-Object { Stop-Process -Id $_.ProcessId -Force }
          Get-CimInstance Win32_Process |
            Where-Object { $_.Name -eq 'java.exe' -and $_.CommandLine -match 'joana\.jar' } |
            ForEach-Object { Stop-Process -Id $_.ProcessId -Force }

      # 3. Ambiente Node
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Node deps
        working-directory: src/main/javascript
        run: npm ci

      - name: Build (caso tenha script)
        working-directory: src/main/javascript
        run: npm run build --if-present

      # 4. Build Java/Maven (usa JDK‑21 exposto no passo 0)
      - name: Build joana.jar
        run: mvn -B clean package -DskipTests

      # 5. Deploy artefatos
      - name: Deploy artefatos
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          
          $prodRoot = 'C:\Apps\Joana'
          $nodeDst  = Join-Path $prodRoot 'js'
          $jarDst   = Join-Path $prodRoot 'joana.jar'
          
          if (-not (Test-Path $prodRoot)) { New-Item -ItemType Directory -Path $prodRoot -Force | Out-Null }
          if (-not (Test-Path $nodeDst))  { New-Item -ItemType Directory -Path $nodeDst  -Force | Out-Null }
          
          # --- copia JAR ---
          $jar = Get-ChildItem "$env:GITHUB_WORKSPACE\target" -Filter 'joana*.jar' | Select-Object -First 1
          if (-not $jar) { throw 'JAR não encontrado.' }
          Copy-Item $jar.FullName $jarDst -Force
          
          # --- sincroniza código Node ---
          $nodeSrc = Join-Path $env:GITHUB_WORKSPACE 'src\main\javascript'
          $distDir = Join-Path $nodeSrc 'dist'
          
          if (Test-Path $distDir) {
          robocopy $distDir $nodeDst /MIR /NFL /NDL /NJH /NJS /NP | Out-Null
          } else {
          robocopy $nodeSrc $nodeDst /MIR /XF package*.json /NFL /NDL /NJH /NJS /NP | Out-Null
          }



      # 6. Relança Node + Java
      - name: Iniciar Joana Node + Java
        shell: powershell
        run: |
          $prodRoot = "C:\Apps\Joana"
          $nodeDir  = "$prodRoot\js"
          Start-Process -FilePath "node.exe" -WorkingDirectory $nodeDir -ArgumentList "index.js" -WindowStyle Hidden
          Start-Process -FilePath "java.exe" -WorkingDirectory $prodRoot -ArgumentList "-jar joana.jar" -WindowStyle Hidden
